set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_SYSTEM_NAME DOS)
set(CMAKE_SYSTEM_PROCESSOR x86)

set(CMAKE_C_COMPILER i586-pc-msdosdjgpp-gcc)
set(CMAKE_CXX_COMPILER i586-pc-msdosdjgpp-g++)

# where is the target environment
# set(CMAKE_FIND_ROOT_PATH $ENV{DJDIR})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_Fortran_COMPILER i586-pc-msdosdjgpp-gfortran)
set(CMAKE_AR:FILEPATH i586-pc-msdosdjgpp-ar)
set(CMAKE_RANLIB:FILEPATH i586-pc-msdosdjgpp-ranlib)